name: Rust Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src-tauri/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src-tauri/**'

env:
  CARGO_TERM_COLOR: always
  RUST_LOG: debug
  RUST_BACKTRACE: 1

jobs:
  test:
    name: Run Rust Tests
    runs-on: macos-latest
    defaults:
      run:
        working-directory: ./src-tauri

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: "src-tauri -> target"

    - name: Run tests
      run: cargo test -- --nocapture
